# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeTheSlaves2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeTheSlaves2
pod ‘Firebase/Core’
pod 'Firebase/Database'
  target 'FreeTheSlaves2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
